### ISSUE TITLE
Option to pass JVM arguments

### ISSUE THREAD

**Issue by jcayzac** [krisztianb/plantuml-pipe#2]
Without the option to pass arguments to `java` when starting the PlantUML JAR, this makes this module unusable for complex diagrams which require a bigger heap.

**Comment by krisztianb** [comment]
Thank you for your feedback. I added two options in the new release:
* javaOptions = These are passed as options to the JAVA process. This is what you were asking for.
* plantUmlArgs = These are passed to the JAVA process but as arguments to the JAR.
