### ISSUE TITLE
vizjs or graphviz installation

### ISSUE THREAD

**Issue by sylvainar** [krisztianb/plantuml-pipe#4]
vizjs or graphviz should be installed with plantuml to avoid external java dependencies

**Comment by krisztianb** [comment]
Vizjs seems to be discontinued: https://github.com/mdaines/viz.js

I think it is out of the scope of this package to install an external peer dependency. But I could create a post install script that at least checks if the dependency is missing and outputs an error message in that case.

**Comment by krisztianb** [comment]
Post install testdot script added in 1.3.2. 👍
